# Header
menu:
  Home: /
  Archives: /archive
rss: /atom.xml

# Content
excerpt_link: Leia mais
fancybox: false

# Sidebar
sidebar: left
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-74900050-1
favicon: 
twitter:
google_plus:
fb_admins:
fb_app_id: 1702261433392463
