baseURL = "http://raphaklaus.com"
DefaultContentLanguage = "en"
title = "raphaklaus"
theme="minimax"
disqusShortname = "raphaklaus"

[Languages]
[Languages.en]
languageName = "English"
[Languages.pt-br]
languageName = "Portuguese"