baseURL = "http://raphaklaus.com"
DefaultContentLanguage = "en"
title = "Raphael D. Pinheiro"
theme = "minimax"
disqusShortname = "raphaklaus"
enableRobotsTXT = true

[Languages]
[Languages.en]
  languageName = "English"
  languageCode = "en_US"
[Languages.pt-br]
  languageName = "Portuguese"
  languageCode = "pt_BR"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"