categories: Categorias
search: Busca
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Anterior
next: Próximo
comment: Comentários
archive_a: Artigos
archive_b: "Artigos: %s"
page: Página %d
recent_posts: Posts recentes
newer: Novos
older: Velhos
share: Compartilhar
powered_by: Powered by
rss_feed: RSS Feed
category: Categoria
tag: Tag